version: "3.9"
services:
  db:
    image: postgres:14.5
    container_name: pg
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgres/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ns6qLf6S
      POSTGRES_DB: mpg_project
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  military:
    depends_on:
      - db
    env_file:
      - .env
    image: military-service
    container_name: military-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mpg_project
    restart: always
  provinces:
    depends_on:
      - db
    env_file:
      - .env
    image: provinces-service
    container_name: provinces-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mpg_project
    restart: always



